export const recipes = [
  {
    recipeId: 10,
    title: 'Spaghetti Meatballs',
    photoUrl: 'https://www.irenemilito.it/wp-content/uploads/2019/12/1506456062-delish-spaghetti-meatballs.jpg',
    time: '60',
    ingredients: [
      ['Meat', '500g'],
      ['Tomato Passata', '750ml'],
      ['Oregano', '1tbsp'],
      ['Spaghetti', '100g'],
    ],
  },
  {
    recipeId: 11,
    title: 'Chicken Katsu',
    photoUrl: 'https://images.japancentre.com/recipes/pics/301/main/301_Chicken_Katsu_Curry.jpg?1469573012',
    time: '30',
    ingredients: [
      ['Chicken', '500g'],
      ['Onion', '2pc'],
      ['Carrots', '500g'],
      ['Curry Spice', '1tbsp'],
      ['Rice', '1cup'],
    ],
  },
  {
    recipeId: 12,
    title: 'Butter Chicken',
    photoUrl: 'https://easychickenrecipes.com/wp-content/uploads/2019/11/butter-chicken-reshoot-6-of-8-500x500.jpg',
    time: '60',
    ingredients: [
      ['Meat', '500g'],
      ['Tomato Passata', '750ml'],
      ['Oregano', '1tbsp'],
      ['Spaghetti', '100g'],
    ],
  },
  {
    recipeId: 13,
    title: 'Chicken Pesto Pasta',
    photoUrl: 'https://www.thewholesomedish.com/wp-content/uploads/2015/04/Chicken-Pesto-Pasta-016.jpg',
    time: '30',
    ingredients: [
      ['Chicken', '500g'],
      ['Onion', '2pc'],
      ['Carrots', '500g'],
      ['Curry Spice', '1tbsp'],
      ['Rice', '1cup'],
    ],
  },
  {
    recipeId: 14,
    title: 'Chicken Fajitas',
    photoUrl: 'https://www.cookingclassy.com/wp-content/uploads/2020/03/chicken-fajitas-18.jpg',
    time: '60',
    ingredients: [
      ['Meat', '500g'],
      ['Tomato Passata', '750ml'],
      ['Oregano', '1tbsp'],
      ['Spaghetti', '100g'],
    ],
  },
  {
    recipeId: 15,
    title: 'Chocolate chip cookies',
    photoUrl: 'https://t8x8a5p2.stackpathcdn.com/wp-content/uploads/2020/06/Chocolate-Chip-Cookies-Recipe-720x720.jpg',
    time: '30',
    ingredients: [
      ['Chicken', '500g'],
      ['Onion', '2pc'],
      ['Carrots', '500g'],
      ['Curry Spice', '1tbsp'],
      ['Rice', '1cup'],
    ],
  },
  {
    recipeId: 16,
    title: 'Burger and fries',
    photoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT9FkDlA6UeSfwyPGgpTarIgoFPEVZWDXuP4g&usqp=CAU',
    time: '30',
    ingredients: [
      ['Chicken', '500g'],
      ['Onion', '2pc'],
      ['Carrots', '500g'],
      ['Curry Spice', '1tbsp'],
      ['Rice', '1cup'],
    ],
  },
  {
    recipeId: 17,
    title: 'Bahmi',
    photoUrl: 'https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/24/03/80/picwqsOVR.jpg',
    time: '30',
    ingredients: [
      ['Chicken', '500g'],
      ['Onion', '2pc'],
      ['Carrots', '500g'],
      ['Curry Spice', '1tbsp'],
      ['Rice', '1cup'],
    ],
  },
  {
    recipeId: 18,
    title: 'Pizza',
    photoUrl: 'https://www.moulinex-me.com/medias/?context=bWFzdGVyfHJvb3R8MTQzNTExfGltYWdlL2pwZWd8aDM2L2g1Mi8xMzA5NzI3MzI2MjExMC5qcGd8N2MxZDhmNmI5ZTgzZDZlZWQyZGQ4YjFlZjUyNDlkMTExYjdkZDdlZmFkY2I0N2NmNjljOGViNmExZjIyMDU4Yw',
    time: '30',
    ingredients: [
      ['Chicken', '500g'],
      ['Onion', '2pc'],
      ['Carrots', '500g'],
      ['Curry Spice', '1tbsp'],
      ['Rice', '1cup'],
    ],
  },
]